-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 21:21:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema capstone2020
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `capstone2020` ;

-- -----------------------------------------------------
-- Schema capstone2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstone2020` DEFAULT CHARACTER SET utf8 ;
USE `capstone2020` ;

-- -----------------------------------------------------
-- Table `capstone2020`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`bill` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`bill` (
  `billID` INT(11) NOT NULL AUTO_INCREMENT,
  `totalAmount` DECIMAL(10,2) NOT NULL,
  `tableID` INT(11) NOT NULL,
  PRIMARY KEY (`billID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `capstone2020`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`category` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`category` (
  `categoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(30) NOT NULL,
  `menuID` INT(11) NOT NULL,
  PRIMARY KEY (`categoryID`),
  UNIQUE INDEX `categoryName` (`categoryName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Meal category';


-- -----------------------------------------------------
-- Table `capstone2020`.`help`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`help` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`help` (
  `helpID` INT(11) NOT NULL,
  `helpStatusID` INT(11) NOT NULL,
  `tableID` INT(11) NOT NULL,
  PRIMARY KEY (`helpID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `capstone2020`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`survey` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`survey` (
  `surveyID` INT(11) NOT NULL AUTO_INCREMENT,
  `surveyA1` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA2` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA3` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA4` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA5` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA6` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA7` DECIMAL(2,1) NULL DEFAULT NULL,
  `surveyA8` DECIMAL(2,1) NULL DEFAULT NULL,
  PRIMARY KEY (`surveyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `capstone2020`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`table` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`table` (
  `tableID` INT NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endTime` DATETIME NULL,
  `totalAmont` DOUBLE NOT NULL DEFAULT 0.0,
  `tableStatus` INT NOT NULL DEFAULT 0,
  `helpID` INT NOT NULL,
  `billID` INT NOT NULL,
  `surveyID` INT NOT NULL,
  `survey_surveyID` INT(11) NOT NULL,
  `help_helpID` INT(11) NOT NULL,
  `bill_billID` INT(11) NOT NULL,
  PRIMARY KEY (`tableID`, `startTime`),
  INDEX `fk_table_survey1_idx` (`survey_surveyID` ASC),
  INDEX `fk_table_help1_idx` (`help_helpID` ASC),
  INDEX `fk_table_bill1_idx` (`bill_billID` ASC),
  CONSTRAINT `fk_table_survey1`
    FOREIGN KEY (`survey_surveyID`)
    REFERENCES `capstone2020`.`survey` (`surveyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table_help1`
    FOREIGN KEY (`help_helpID`)
    REFERENCES `capstone2020`.`help` (`helpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table_bill1`
    FOREIGN KEY (`bill_billID`)
    REFERENCES `capstone2020`.`bill` (`billID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone2020`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`order` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `orderItem` INT NOT NULL DEFAULT 0,
  `orderItemQty` INT NOT NULL DEFAULT 0 COMMENT 'order list',
  `orderAmount` DOUBLE NOT NULL,
  `orderStatus` INT NOT NULL DEFAULT 0,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `table_tableID` INT NOT NULL,
  `table_startTime` DATETIME NOT NULL,
  PRIMARY KEY (`orderID`, `orderItem`),
  UNIQUE INDEX `orderedItemQty_UNIQUE` (`orderItemQty` ASC),
  INDEX `fk_order_table1_idx` (`table_tableID` ASC, `table_startTime` ASC),
  CONSTRAINT `fk_order_table1`
    FOREIGN KEY (`table_tableID` , `table_startTime`)
    REFERENCES `capstone2020`.`table` (`tableID` , `startTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone2020`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capstone2020`.`item` ;

CREATE TABLE IF NOT EXISTS `capstone2020`.`item` (
  `itemID` INT(11) NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(255) NOT NULL,
  `itemPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  `itemDesc` VARCHAR(255) NULL DEFAULT NULL,
  `categoryID` INT(11) NOT NULL,
  `photoLocalDirectory` VARCHAR(255) NULL DEFAULT NULL,
  `photoCloudDirectory` VARCHAR(255) NULL DEFAULT NULL,
  `order_orderID` INT NOT NULL,
  `order_orderItem` INT NOT NULL,
  PRIMARY KEY (`itemID`),
  UNIQUE INDEX `itemName` (`itemName` ASC),
  INDEX `item_fk` (`categoryID` ASC),
  INDEX `fk_item_order1_idx` (`order_orderID` ASC, `order_orderItem` ASC),
  CONSTRAINT `item_fk`
    FOREIGN KEY (`categoryID`)
    REFERENCES `capstone2020`.`category` (`categoryID`),
  CONSTRAINT `fk_item_order1`
    FOREIGN KEY (`order_orderID` , `order_orderItem`)
    REFERENCES `capstone2020`.`order` (`orderID` , `orderItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Meal items';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
